---
title: "Research"
format: html
---
# Job Market Paper 
<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=6760018">Link to the preprint.</a>

# Publications
Krafft, C., West, K., McFarlane, A., <b>Kula, E.</b>, Abdinoor, F., Weyrens-Welch, M., & Drain, K. (2023). Virtually Nonexistent: Gender and Racial Representation in Online K-12 Economics Lessons. <em>Eastern Economic Journal</em>, 49(1), 78-87. <a href="https://doi.org/10.1057/s41302-022-00231-0">10.1057/s41302-022-00231-0</a>

Krafft, C., <b>Kula, E.</b>, & Sieverding, M. (2021). An investigation of Jordan’s fertility stall and resumed decline. <em>Demographic Research</em>, 45, 605-652. <a href="https://www.jstor.org/stable/48640790">https://www.jstor.org/stable/48640790</a>

# Works in Progress

**Libby Kula, Ben Janke, Justin A. Johnson, Yanxu Long, Eric Lonsdorf, Chris Nootenboom, & Stephen Polasky. 
Submitted for publication. “Urban ecosystem services in decline: The cost of urban expansion in U.S. 
metropolitan areas from 2001 to 2021.”**  
 Abstract: We quantify access to green space, and the monetary ecosystem service values for urban cooling, stormwater retention, and carbon storage for 380 metropolitan areas in the contiguous U.S. in 2001, 2011, and 2021, using the Urban Integrated Valuation of Ecosystem Services and Tradeoffs (Urban InVEST) software. We find significant values of ecosystem services in urban areas, $1.5 billion in urban cooling from reduced energy expenditures, $20.3 billion in reduced stormwater retention costs, and $24.6 billion in the annual rental value of carbon storage in 2021. However, we find decreases in the provision of ecosystem services over the 20-year period across most metropolitan areas, reflecting a loss of urban green space. The rate of loss has slowed over time with greater losses from 2001 to 2011 than from 2011 to 2021.

**Libby Kula. In Progress. “How equitably are ecosystem services distributed in U.S. metropolitan areas?” **  
 Abstract: Using Urban Integrated Valuation of Ecosystem Services and Tradeoffs (Urban InVEST) results for the ecosystem services of urban cooling and urban nature access for the years 2001, 2011, and 2021 for 380 metropolitan areas in the contiguous U.S., I analyze the distribution of these ecosystem services,
 a.k.a. ecosystem services inequality (ESI), across various socioeconomic variables. I find significant inequities in the provision of ecosystem services across socioeconomic status, race and ethnic minority status, household characteristics, and housing type and transportation. In some cases, the amount of energy savings from urban cooling experienced by disadvantaged communities is roughly half that of the advantaged metropolitan population. For 2021, Census tracts with a relatively high proportion of people of color have less
 than 1/4 of the urban nature supply per capita of relatively white tracts. I find inequities in ecosystem services provision typically persist, and in some cases worsen, over the 20-year period of study.